

test:
	PYTHONPATH='..' pytest -v -x tests.py

retest:
	PYTHONPATH='..' pytest --lf -v -x tests.py

debug:
	PYTHONPATH='..' pytest -v -x --pdb tests.py

redebug:
	PYTHONPATH='..' pytest --lf -v -x --pdb tests.py
